title: "Crop - Intelligent Image Cropping Library"
description: "PHP library for intelligent image cropping with multiple algorithms"
url: "https://drzippie.github.io"
baseurl: "/crop"

# Jekyll configuration
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - installation.md
  - usage.md
  - strategies.md
  - examples/index.md
  - api/index.md

# Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:name/
  api:
    output: true
    permalink: /:collection/:name/

# Social links
github_username: drzippie
repository: drzippie/crop

# SEO
twitter:
  username: drzippie
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/